# Generated by Django 5.1 on 2025-02-02 02:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('other_names', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Names')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], default='prefer_not_to_say', max_length=20, verbose_name='Gender')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('id_type', models.CharField(blank=True, choices=[('national_ID', 'National ID'), ('driver_license', 'Driver’s License'), ('passport', 'Passport'), ('others', 'Others')], max_length=25, null=True, verbose_name='ID Type')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Number')),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='ID Image')),
                ('address', models.TextField(blank=True, max_length=400, null=True, verbose_name='Address')),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cash Balance')),
                ('coins', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Coins Balance')),
                ('rank', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=10, verbose_name='Rank')),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Lower Limit')),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Upper Limit')),
                ('verification_status', models.BooleanField(default=False, verbose_name='Verification Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('twitter_profile', models.URLField(blank=True, null=True, verbose_name='Twitter Profile')),
                ('facebook_profile', models.URLField(blank=True, null=True, verbose_name='Facebook Profile')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'), models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['slug'], name='users_user_slug_04b338_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
